simulation:
  hlr: 0.5
  flux: 1.0
  psf_npix: 51
  psf_noise: 1.0e-6
  scale: 0.141
  npix: 64
  nse_sd: 1.0e-6
  seed: 150
  n_obs: 200000
  psfex_model_file: "/home/adfield/SHEARNET_DATA/psfex-output/Abell3411_1_300_1683033980_clean_starcat.psf"

output:
  results_fits: "psf_leakage_results_200k.fits"

models:
  psf_model: "em5"
  gal_model: "gauss"

catalog:
  cosmos_cat_fname: "/home/adfield/ShearNet/cosmos15_superbit2023_phot_shapes_with_sigma.csv"
