# shearnet/config/default_config.yaml
# Default configuration for ShearNet

# Dataset configuration
dataset:
  samples: 10000
  psf_sigma: 0.25
  exp: "ideal"
  nse_sd: 1.0e-5
  seed: 42
  stamp_size: 53
  pixel_size: 0.141
  apply_psf_shear: false
  psf_shear_range: 0.05

# Model configuration (for regular shear training)
model:
  process_psf: false
  type: "cnn"  # Options: mlp, cnn, resnet, forklens_psf, research_backed, fork-like
  galaxy:
    type: "research_backed"
  psf:
    type: "forklens_psf"

# Deconvolution model configuration (for deconv training)
deconv:
  model_type: "unet"  # Options: unet
  
# Training configuration
training:
  epochs: 10
  batch_size: 32
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  patience: 10
  val_split: 0.2
  eval_interval: 1
  
# Evaluation configuration
evaluation:
  test_samples: 1000
  seed: 58
  compare_ngmix: true
  
# Output configuration
output:
  save_path: null  # Will use SHEARNET_DATA_PATH/model_checkpoint if null
  plot_path: null  # Will use SHEARNET_DATA_PATH/plots if null
  model_name: "my_model"
  
# Plotting configuration
plotting:
  plot: true
  
# Comparison methods
comparison:
  mcal: true
  ngmix: true
  psf_model: "gauss"
  gal_model: "gauss"