# shearnet/config/default_config.yaml
# Default configuration for ShearNet

# Dataset configuration
dataset:
  samples: 10000
  psf_sigma: 0.25
  exp: "ideal"
  nse_sd: 1.0e-5
  seed: 42
  stamp_size: 53
  pixel_size: 0.141

# Model configuration  
model:
  type: "cnn"  # Options: mlp, cnn, resnet
  
# Training configuration
training:
  epochs: 10
  batch_size: 32
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  patience: 10
  val_split: 0.2
  eval_interval: 1
  
# Evaluation configuration
evaluation:
  test_samples: 1000
  seed: 58
  
# Output configuration
output:
  save_path: null  # Will use SHEARNET_DATA_PATH/model_checkpoint if null
  plot_path: null  # Will use SHEARNET_DATA_PATH/plots if null
  model_name: "my_model"
  
# Plotting configuration
plotting:
  plot: true  # Whether to plot learning curves
  
# Comparison methods
comparison:
  mcal: true
  ngmix: true
  psf_model: "gauss"
  gal_model: "gauss"