simulation:
  hlr: 0.5
  flux: 12258.97
  psf_fwhm: 0.5
  scale: 0.141
  npix: 63
  nse_sd: 12
  seed: 150
  n_obs: 30000
  Njack: 20
  shear_true: 0.02

output:
  pdf_name: "sample_galaxies_triplet.pdf"

models:
  psf_model: "gauss"
  gal_model: "gauss"

catalog:
  cosmos_cat_fname: "/projects/mccleary_group/superbit/galsim_data/cosmos15_superbit2023_phot_shapes_with_sigma.csv"
