# Dataset configuration

schema_version: 1
run_options:
  run_name: FIRST_const_sigma+flux_nse_sd_12_type_exp
simulation:
  psf:
    gaussian_fwhm: 0.25
    mode: superbit
  noise_sigma: 12.719674
model:
  type: fork-like
training:
  nobj: 100000
  epochs: 300
  batch_size: 128
  patience: 25
evaluation:
  nobj: 50000
