# Dataset configuration

schema_version: 1
run_options:
  run_name: fork-like_superbit_low-noise
simulation:
  psf:
    gaussian_fwhm: 0.25
    mode: superbit
model:
  type: fork-like
training:
  nobj: 100000
  epochs: 300
  batch_size: 128
  patience: 25
evaluation:
  nobj: 5000
