simulation:
  hlr: 0.5
  flux: 12258.97
  psf_fwhm: 0.5
  psf_npix: 53
  psf_noise: 1.0e-6
  scale: 0.141
  npix: 53
  nse_sd: 12.719674
  seed: 150
  n_obs: 100000
  Njack: 20
  shear_true: 0.01

output:
  results_fits: "metacal_results.fits"
  # pdf_name: "sample_galaxies_triplet.pdf"

models:
  psf_model: "gauss"
  gal_model: "gauss"

catalog:
  cosmos_cat_fname: "/home/adfield/ShearNet/cosmos15_superbit2023_phot_shapes_with_sigma.csv"
