# Dataset configuration

schema_version: 1
run_options:
  run_name: fork-like_ideal_low-noise
simulation:
  psf:
    gaussian_fwhm: 0.25
model:
  type: fork-like
training:
  nobj: 200
  epochs: 300
  batch_size: 128
  patience: 25
evaluation:
  nobj: 50
