# Dataset configuration
dataset:
  samples: 500
  psf_sigma: 0.25
  exp: "ideal"
  nse_sd: 1.0e-5
  seed: 42
  stamp_size: 53
  pixel_size: 0.141
  apply_psf_shear: false
  psf_shear_range: 0.05

# Deconvolution model configuration  
deconv:
  model_type: "research_backed"  # Options: base, enhanced, research_backed
  
# Training configuration
training:
  epochs: 5
  batch_size: 10
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  patience: 30
  val_split: 0.2
  eval_interval: 1
  weights: [0.2, 0.5, 0.05, 0.05]
  
# Evaluation configuration
evaluation:
  test_samples: 50
  seed: 58
  
# Output configuration
output:
  save_path: null  # Will use SHEARNET_DATA_PATH/model_checkpoint if null
  plot_path: null  # Will use SHEARNET_DATA_PATH/plots if null
  model_name: "deconv_dry_run"
  
# Plotting configuration
plotting:
  plot: true
  num_plot_samples: 3