# Dataset configuration
dataset:
  samples: 10000
  psf_sigma: 0.25
  exp: "ideal"
  nse_sd: 1.0e-5
  seed: 42
  stamp_size: 53
  pixel_size: 0.141
  apply_psf_shear: true
  psf_shear_range: 0.05

# Deconvolution model configuration  
deconv:
  model_type: "unet"  # Options: unet, simple
  loss_type: "mse"    # Options: mse, perceptual
  
# Training configuration
training:
  epochs: 300
  batch_size: 128
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  patience: 20
  val_split: 0.2
  eval_interval: 1
  
# Evaluation configuration
evaluation:
  test_samples: 5000
  seed: 58
  
# Output configuration
output:
  save_path: null  # Will use SHEARNET_DATA_PATH/model_checkpoint if null
  plot_path: null  # Will use SHEARNET_DATA_PATH/plots if null
  model_name: "deconv_large_test"
  
# Plotting configuration
plotting:
  plot: true
  num_plot_samples: 3