# configs/dry_run.yaml
dataset:
  samples: 100
  psf_fwhm: 0.25
  nse_sd: 1.0e-2
  exp: "ideal"
  seed: 42
  stamp_size: 53
  pixel_size: 0.141
  # PSF shear configuration
  apply_psf_shear: false
  psf_shear_range: 0.05
  hlr_type: "constant"
  flux_type: "constant"

model:
  process_psf: true
  type: "fork-like"  # Options: mlp, cnn, resnet, forklens_psf, 
               #          research_backed, and fork-like
  galaxy:
    type: "research_backed"
  psf:
    type: "forklens_psf"
  output_keys: ['g1', 'g2']
  gap: False

training:
  epochs: 10
  batch_size: 16
  patience: 20
  loss_weights: [1.0, 1.0] # one weight per output_key, in order

evaluation:
  test_samples: 10
  seed: 58

output:
  model_name: "dry_run"
  
plotting:
  plot: true

# Comparison methods
comparison:
  ngmix: true
  psf_model: "gauss"
  gal_model: "gauss"
