# Current state:
# So everything is set up to predict all four parameters. I accidentally overwrote the first_validation_test_no_sigma_flux_preds learning_curve, so retrain the two parameter prediction model, then retrain the four parameter prediction model.

# Dataset configuration

schema_version: 1
run_options:
  run_name: first_validation_test_4_params
simulation:
  noise_sigma: 12.719674
model:
  type: fork-like
training:
  nobj: 100000
  epochs: 300
  batch_size: 128
  learning_rate: 0.0001
  patience: 50
evaluation:
  nobj: 30000
