# Dataset configuration

schema_version: 1
run_options:
  run_name: fork-like_-3_noise_superbits
simulation:
  psf:
    gaussian_fwhm: 0.25
    mode: superbit
  noise_sigma: 0.001
model:
  type: fork-like
training:
  nobj: 100000
  epochs: 300
  batch_size: 128
  patience: 25
evaluation:
  nobj: 5000
