dataset:
  samples: 100000
  psf_sigma: 0.25
  exp: "ideal"
  nse_sd: 1.0e-5
  seed: 42
  stamp_size: 53
  pixel_size: 0.141
  apply_psf_shear: true
  psf_shear_range: 0.05

deconv:
  model_type: "research_backed"
  architecture: "full"
  encoder_features: [64, 128, 256, 512, 1024]
  use_transformers: true
  use_physics_informed: true
  use_dense_connections: true
  use_pyramid_fusion: true
  window_size: 8
  num_heads: 8
  dropout_rate: 0.1

training:
  epochs: 200
  batch_size: 8
  learning_rate: 3.0e-4
  weight_decay: 1.0e-4
  patience: 30
  val_split: 0.2
  eval_interval: 1

evaluation:
  test_samples: 5000
  seed: 58
  compare_ngmix: true

output:
  model_name: "research_backed_max_performance"

plotting:
  plot: true
  num_plot_samples: 10