# Dataset configuration

schema_version: 1
run_options:
  run_name: old-cnn_superbit_high-noise
simulation:
  psf:
    gaussian_fwhm: 0.25
    mode: superbit
  noise_sigma: 0.01
training:
  nobj: 100000
  epochs: 300
  batch_size: 128
  patience: 25
evaluation:
  nobj: 5000
